# Generated by Django 2.0.7 on 2018-07-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogsPost',
            new_name='Home',
        ),
    ]
