# Generated by Django 2.0.7 on 2018-08-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='匿名', max_length=20)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
